apiVersion: extensions/v1beta1 #apps/v1beta2 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: project-data-tier
spec:
  replicas: 1
  template:
    metadata:
      name: project-data-tier
      labels:
        app: project
        tier: data
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              protocol: TCP