apiVersion: v1
kind: Service
metadata:
  name: project-app-tier-be
spec:
  type: LoadBalancer
  selector:
    app: project
    tier: app
  ports:
    - name: app
      port: 80
      targetPort: 8080
      protocol: TCP